CC = g++
TARGET = TopSortMain
OBJ = TopSortMain.o

$(TAREGT) : $(OBJ)
	$(CC) -o $(TARGET) $(OBJ)

INCLUDE = -I../
CXXFLAGS = $(INCLUDE)

$(OBJ) : TopSortMain.cpp
	$(CC) -c TopSortMain.cpp $(CXXFLAGS)

